---
- import_tasks: check_system.yml

- name: Add repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: App repository
  apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    filename: docker

- name: Install linux-image-extras
  shell: apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual
  when: ansible_distribution_version == '14.04'

- name: Refine docker version
  shell: "apt-cache madison {{ docker_package }} | grep {{ docker_version }} | head -n 1 | cut -d ' ' -f 4"
  register: docker_version_name
  when: docker_version is defined

#- debug:
#    msg: "docker_package:{{ docker_package }}  docker_version_name:{{ docker_version_name }}"

#- fail:

- name: Define docker-ce package name and version to install
  set_fact: { docker_package: "{{ docker_package }}={{ docker_version_name.stdout }}" }
  when: docker_version_name is defined and docker_version_name.stdout is defined and docker_version_name.stdout != ''

- name: Install packages
  apt: name={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - "{{ docker_package }}"

- name: Start docker
  service: name=docker state=restarted enabled=yes
  when: ansible_distribution_release == "trusty"

- name: Start docker
  systemd: name=docker state=restarted enabled=yes
  when: ansible_distribution_release == "xenial"
