---
- import_tasks: check_system.yml
- import_tasks: check_variables.yml

- name: Check if docker is installed
  command: docker
  register: docker_install_check
  ignore_errors: yes

- name: Import tasks
  import_tasks: install_on_xenial.yml
  when: docker_install_check.failed
